name: Test against supported Java versions

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  RABBITMQ_IMAGE_TAG: 3.11
  RABBITMQ_IMAGE: rabbitmq

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [ '11', '17', '19', '20-ea', '21-ea' ]
    name:  Test against Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK for compilation
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'
      - name: Show version
        run: ./mvnw --version
      - name: Compile
        run: ./mvnw clean test-compile --no-transfer-progress
      - name: Start RabbitMQ application
        run: ci/start-broker.sh
      - name: Configure broker
        run: HOP_RABBITMQCTL=DOCKER:rabbitmq ci/before-build.sh
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Show version
        run: ./mvnw --version
      - name: Test
        run: ./mvnw test -DskipBytecodeCheck --no-transfer-progress
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq