name: Test against supported Java versions

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [ '11', '17', '21' ]
    name:  Test against Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Start RabbitMQ
        run: ci/start-broker.sh
      - name: Configure broker
        run: HOP_RABBITMQCTL=DOCKER:rabbitmq ci/before-build.sh
      - name: Show version
        run: ./mvnw --version
      - name: Test
        run: ./mvnw test --no-transfer-progress
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq
